### ISSUE TITLE
Error opening any input file

### ISSUE THREAD

**Issue by grigger74** [the-database/VideoJaNai#26]
> ffmpeg version 2024-08-07-git-94165d1b79-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59. 32.100 / 59. 32.100
  libavcodec     61. 11.100 / 61. 11.100
  libavformat    61.  5.101 / 61.  5.101
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Script evaluation failed:
Python exception: could not convert string to float: ''
Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3374, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3375, in vapoursynth._vpy_evaluate
  File "C:\Users\1\Documents\VideoJaNai-win-Portable\current\backend\animejanai\core\animejanai_encode.vpy", line 6, in <module>
    import animejanai_core
  File "C:\Users\1\Documents\VideoJaNai-win-Portable\current\backend\animejanai\core\animejanai_core.py", line 312, in <module>
    init()
  File "C:\Users\1\Documents\VideoJaNai-win-Portable\current\backend\animejanai\core\animejanai_core.py", line 303, in init
    config = animejanai_config.read_config()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Documents\VideoJaNai-win-Portable\current\backend\animejanai\core\animejanai_config.py", line 186, in read_config
    conf[section][f'chain_{int(chain)}'] = read_config_by_chain(flat_conf, section, int(chain), len(all_models))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Documents\VideoJaNai-win-Portable\current\backend\animejanai\core\animejanai_config.py", line 60, in read_config_by_chain
    'rife_model': int(float(flat_conf[section].get(f'chain_{chain}_rife_model', 414))),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
[in#0 @ 00000219b81d0640] Error opening input: Invalid data found when processing input
Error opening input file pipe:.
Error opening input files: Invalid data found when processing input

**Comment by AvoidantPerDis** [comment]
same

**Comment by illeatmyhat** [comment]
If we look in the `animejanai.conf` file, there's an empty field
`chain_1_rife_model=`
which appears to be the issue here.
This is caused by interpolation being disabled, and the config function not accounting for this path.

**Comment by the-database** [comment]
Thanks for the info, this is fixed in v1.1.0.
